 import type { Story } from "@/types/content";

// Backup reconstruido a partir do conteudo que existia localmente antes da migracao
// para o Supabase. Este arquivo nao e usado pelo app atual.
export const legacyStories: Story[] = [
  {
    id: "raposa-estrelas",
    title: "A Raposa que Colecionava Estrelas",
    author: "Marina Luz",
    description:
      "Uma pequena raposa curiosa parte pela floresta atrás das estrelas que caem toda noite.",
    categoryId: "animais",
    emoji: "🦊",
    image: "/stories/raposa-estrelas.png",
    gradient: "from-orange-300 via-amber-300 to-yellow-200",
    minutes: 6,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Era uma vez uma raposinha chamada Fifi que morava perto da colina florida.",
      "Toda noite, Fifi via estrelas caindo do céu e queria descobrir onde elas iam parar.",
      "Certa noite, ela seguiu uma trilha brilhante até um lago escondido cheio de luzinhas...",
      "As estrelas dançavam na água! Fifi guardou uma no bolso e voltou para casa sorrindo.",
    ],
  },
  {
    id: "castelo-nuvens",
    title: "O Castelo Acima das Nuvens",
    author: "Tomás Vento",
    description:
      "Duas crianças descobrem uma escada mágica que leva a um castelo flutuante.",
    categoryId: "fantasia",
    emoji: "🏰",
    image: "/stories/castelo-nuvens.png",
    gradient: "from-sky-300 via-indigo-300 to-purple-400",
    minutes: 8,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 3,
    pages: [
      "Bia e Nico encontraram uma escada dourada aparecendo no fundo do quintal.",
      "Subiram, subiram... até chegar num castelo feito de nuvens fofinhas.",
      "Lá conheceram o Rei do Vento, que lhes ensinou a assobiar canções da chuva.",
    ],
  },
  {
    id: "foguete-limao",
    title: "O Foguete de Limão",
    author: "Sofia Cometa",
    description:
      "Um cientista de 7 anos constrói um foguete no quintal — e ele decola de verdade!",
    categoryId: "espaco",
    emoji: "🚀",
    image: "/stories/foguete-limao.png",
    gradient: "from-indigo-400 via-purple-500 to-pink-500",
    minutes: 7,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 3,
    pages: [
      "Otto misturou limão, mel e um pouquinho de imaginação.",
      "O foguete tremeu e subiu direto para a Lua!",
      "Lá, ele plantou uma semente e voltou para o café da manhã.",
    ],
  },
  {
    id: "rex-timido",
    title: "Rex, o Dinossauro Tímido",
    author: "Bento Rocha",
    description:
      "Rex é enorme, mas tem vergonha de rugir. Vai encontrar coragem com um novo amigo?",
    categoryId: "dinossauros",
    emoji: "🦖",
    image: "/stories/rex-timido.png",
    gradient: "from-lime-300 via-green-400 to-emerald-600",
    minutes: 5,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 3,
    pages: [
      "Rex morava numa floresta antiga e nunca ninguém tinha ouvido o seu rugido.",
      "Um passarinho corajoso ensinou Rex a respirar fundo e soltar a voz...",
      "ROOOAAAR! A floresta inteira aplaudiu.",
    ],
  },
  {
    id: "capita-perola",
    title: "Capitã Pérola e o Mapa Perdido",
    author: "Lia Mar",
    description:
      "Uma jovem capitã cruza sete mares atrás de um tesouro que só existe na sua ideia.",
    categoryId: "piratas",
    emoji: "🏴‍☠️",
    image: "/stories/capita-perola.png",
    gradient: "from-amber-300 via-orange-400 to-red-500",
    minutes: 9,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 3,
    pages: [
      "Pérola desenhou um mapa cheio de X vermelhos e zarpou.",
      "Enfrentou tempestades, polvos gentis e uma ilha feita de balas.",
      "O tesouro? Fazer novos amigos em cada porto.",
    ],
  },
  {
    id: "sementinha",
    title: "A Sementinha Curiosa",
    author: "Ana Verde",
    description:
      "Uma sementinha decide não esperar a primavera para ver o mundo.",
    categoryId: "natureza",
    emoji: "🌱",
    image: "/stories/sementinha-curi.png",
    gradient: "from-green-300 via-emerald-400 to-teal-500",
    minutes: 4,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 2,
    pages: [
      "A sementinha espiou pra fora da terra bem antes da hora.",
      "Sentiu chuva, vento, sol — e virou a árvore mais alta do jardim.",
    ],
  },
  {
    id: "laboratorio-luz",
    title: "O Laboratório da Luz",
    author: "Dr. Cléo",
    description:
      "Descubra por que o céu é azul, com experiências malucas de uma cientista curiosa.",
    categoryId: "ciencia",
    emoji: "🔬",
    image: "/stories/laboratorio-luz.png",
    gradient: "from-sky-300 via-blue-400 to-indigo-500",
    minutes: 6,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 2,
    pages: [
      "Cléo pegou uma lanterna, um copo de água e descobriu um arco-íris.",
      "A luz é mágica — e a ciência é a linguagem dessa mágica.",
    ],
  },
  {
    id: "urso-lua",
    title: "O Urso que Comeu a Lua",
    author: "Zé Sonho",
    description:
      "Um urso guloso confunde a lua com um queijo e sai numa aventura noturna.",
    categoryId: "animais",
    emoji: "🐻",
    image: "/stories/urso-lua.png",
    gradient: "from-yellow-200 via-amber-300 to-orange-400",
    minutes: 5,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 2,
    pages: [
      "O urso Bento achou que a lua era um pedaço de queijo.",
      "Subiu na árvore mais alta e mordeu... uma nuvem doce!",
    ],
  },
  {
    id: "dragao-sem-fogo",
    title: "O Dragão que Não Sabia Soltar Fogo",
    author: "Lia Aurora",
    description:
      "Um pequeno dragão tenta descobrir seu dom verdadeiro enquanto todos esperam que ele solte fogo.",
    categoryId: "fantasia",
    emoji: "🐉",
    image: "/stories/dragao-sem-fogo.png",
    gradient: "from-fuchsia-300 via-violet-400 to-indigo-500",
    minutes: 7,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Dudu era um pequeno dragão que vivia no alto da Montanha das Brasas, onde todos os filhotes já treinavam grandes labaredas brilhantes.",
      "Mas, sempre que Dudu enchia o peito e tentava soltar fogo, saíam apenas bolhas coloridas que flutuavam pelo ar e faziam os outros dragões rirem.",
      "Certo dia, uma neblina escura cobriu a montanha e ninguém conseguia enxergar o caminho até as cavernas. Foi então que as bolhas de Dudu começaram a brilhar como lanternas no céu.",
      "Guiados por aquela luz dançante, todos chegaram em segurança. Naquela noite, Dudu descobriu que seu dom não era queimar, e sim iluminar o caminho de quem precisava.",
    ],
  },
  {
    id: "menina-arco-iris",
    title: "A Menina que Encontrou um Arco-Íris",
    author: "Helena Sol",
    description:
      "Uma menina atravessa um arco-íris escondido e descobre um lugar onde cada cor tem um poder diferente.",
    categoryId: "fantasia",
    emoji: "🌈",
    image: "/stories/menina-arco-iris.png",
    gradient: "from-pink-300 via-sky-300 to-violet-400",
    minutes: 7,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Nina adorava subir a colina atrás de casa para ver o céu depois da chuva. Foi lá que ela encontrou um arco-íris escondido atrás da montanha.",
      "Quando tocou a primeira cor com a ponta dos dedos, ouviu um sussurro suave chamando seu nome. Sem pensar duas vezes, atravessou aquele portal brilhante.",
      "Do outro lado havia um vale encantado: o vermelho aquecia corações, o azul acalmava rios, o amarelo fazia flores acordarem, e o verde curava árvores cansadas.",
      "Ao voltar para casa, Nina percebeu que carregava um pedacinho de cada cor dentro de si. Desde então, espalhava coragem, alegria e calma por onde passava.",
    ],
  },
  {
    id: "baleia-estrelas",
    title: "A Baleia que Queria Conhecer as Estrelas",
    author: "Miro Azul",
    description:
      "Uma pequena baleia sonhadora encontra um jeito mágico de tocar o céu e conversar com as estrelas.",
    categoryId: "animais",
    emoji: "🐳",
    image: "/stories/baleia-estrelas.png",
    gradient: "from-sky-300 via-cyan-400 to-indigo-500",
    minutes: 6,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Luna era uma baleinha curiosa que passava as noites boiando na superfície do mar, olhando para o céu como se quisesse guardar cada estrela dentro dos olhos.",
      "Ela perguntava às ondas como podia chegar tão alto, mas as ondas apenas riam e diziam que as estrelas pertenciam ao céu.",
      "Numa noite muito silenciosa, uma estrela cadente caiu sobre o mar e deixou um rastro de luz prateada. Luna seguiu aquele caminho brilhante e sentiu seu coração ficar leve como espuma.",
      "De repente, saltou tão alto que pareceu tocar o firmamento. As estrelas a cumprimentaram com pequenos brilhos, e Luna voltou sabendo que, às vezes, sonhar forte já é um jeito de chegar.",
    ],
  },
  {
    id: "brinquedo-ganhou-vida",
    title: "O Brinquedo que Ganhou Vida",
    author: "Sara Névoa",
    description:
      "Em uma noite de tempestade, um velho ursinho ganha vida e sai do quarto para viver sua primeira aventura.",
    categoryId: "fantasia",
    emoji: "🧸",
    image: "/stories/brinquedo-ganhou-vida.png",
    gradient: "from-amber-200 via-orange-300 to-rose-400",
    minutes: 6,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Durante uma noite de chuva forte, um relâmpago iluminou o quarto de Lia e tocou bem de leve o velho ursinho esquecido na prateleira.",
      "No mesmo instante, os olhinhos de botão se abriram e o ursinho piscou, surpreso por finalmente poder esticar os braços e mexer as patinhas.",
      "Antes que o sol aparecesse, ele decidiu conhecer a casa inteira: atravessou o corredor escuro, desceu a escada rolando devagar e encontrou a cozinha cheirando a biscoito.",
      "Quando voltou para o quarto, o ursinho já não parecia mais esquecido. Lia o abraçou pela manhã e sentiu, sem entender por quê, que ele estava quentinho de aventura.",
    ],
  },
  {
    id: "arvore-segredos",
    title: "A Árvore que Guardava Segredos",
    author: "Ana Serra",
    description:
      "No coração da floresta, uma árvore muito antiga sussurra segredos para quem sabe ouvir com calma.",
    categoryId: "natureza",
    emoji: "🌳",
    image: "/stories/arvore-segredos.png",
    gradient: "from-green-300 via-emerald-500 to-teal-600",
    minutes: 7,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "No meio da floresta existia uma árvore tão antiga que suas raízes pareciam abraçar a terra desde o começo do mundo.",
      "Muitos tentavam arrancar dela respostas apressadas, mas tudo o que ouviam era o balanço das folhas e o vento passando pelos galhos.",
      "Um dia, uma menina chamada Joana sentou-se quietinha ao seu lado e ficou ouvindo o som da mata sem fazer nenhuma pergunta. Então o tronco rangeu baixinho, como se despertasse.",
      "A árvore lhe contou que os rios nascem pacientes, que as sementes crescem no silêncio e que a natureza fala baixinho com quem aprende a escutar de verdade.",
    ],
  },
  {
    id: "passarinho-esqueceu-voar",
    title: "O Passarinho que Esqueceu de Voar",
    author: "Bento Brisa",
    description:
      "Um passarinho descobre que a coragem pode estar escondida bem perto, mesmo quando as asas tremem.",
    categoryId: "animais",
    emoji: "🐦",
    image: "/stories/passarinho-esqueceu-voar.png",
    gradient: "from-yellow-200 via-lime-300 to-sky-400",
    minutes: 6,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Nino acordou numa manhã ensolarada, abriu as asinhas para sair do ninho e, de repente, sentiu um medo tão grande que esqueceu como voar.",
      "Tentou uma vez, depois outra, mas suas penas tremiam e ele logo voltava para o galho, com o coração batendo depressa.",
      "Seus amigos apareceram aos poucos: a borboleta mostrou como confiar no vento, o esquilo ensinou a respirar fundo, e a joaninha disse que coragem também começa pequenininha.",
      "Quando Nino pulou de novo, percebeu que o céu ainda era o mesmo amigo de sempre. E descobriu que voar não era não sentir medo, mas seguir mesmo com as asas tremendo.",
    ],
  },
  {
    id: "relogio-parou-tempo",
    title: "O Relógio que Parou o Tempo",
    author: "Tom Relva",
    description:
      "Um garoto encontra um relógio antigo capaz de parar o tempo e descobre que cada segundo tem valor.",
    categoryId: "ciencia",
    emoji: "⏰",
    image: "/stories/relogio-parou-tempo.png",
    gradient: "from-slate-300 via-sky-400 to-indigo-500",
    minutes: 7,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Miguel encontrou um relógio antigo no fundo de uma lojinha empoeirada, escondido entre mapas rasgados e caixas de música silenciosas.",
      "O vendedor sorriu de um jeito estranho e disse apenas: 'Gire os ponteiros com cuidado'. Curioso, Miguel fez isso assim que chegou em casa.",
      "No mesmo instante, tudo parou. As folhas ficaram imóveis no ar, a água congelou no meio do copo e até o gato do vizinho ficou suspenso num pulo engraçado.",
      "Miguel andou por aquele mundo quieto e percebeu que o tempo é precioso justamente porque nunca fica parado. Quando fez o relógio voltar a funcionar, prometeu aproveitar melhor cada minuto.",
    ],
  },
  {
    id: "concha-historias",
    title: "A Concha que Contava Histórias",
    author: "Clara Maré",
    description:
      "Uma concha encontrada na praia revela aventuras escondidas no fundo do mar sempre que alguém a escuta com atenção.",
    categoryId: "natureza",
    emoji: "🐚",
    image: "/stories/concha-contava-historias.png",
    gradient: "from-cyan-300 via-blue-400 to-teal-500",
    minutes: 6,
    isNew: false,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Sofia passeava pela praia ao amanhecer quando encontrou uma concha diferente, com brilhos cor-de-pérola e desenhos em espiral por toda parte.",
      "Ao encostá-la no ouvido, em vez do som do mar, ela ouviu uma voz suave contando sobre cavalos-marinhos dançarinos e jardins de coral iluminados.",
      "Cada vez que escutava a concha, uma nova aventura aparecia: tartarugas que guardavam mapas, peixes-lanterna que iluminavam cavernas e sereias que sabiam os nomes das estrelas.",
      "Sofia aprendeu que o fundo do mar era feito de histórias esperando alguém parar, escutar e acreditar um pouquinho mais na magia do mundo.",
    ],
  },
  {
    id: "raposa-porta-secreta",
    title: "A Raposa e a Porta Secreta",
    author: "Marina Lua",
    description:
      "Uma raposa encontra uma porta misteriosa na floresta e descobre um lugar onde desejos verdadeiros podem florescer.",
    categoryId: "animais",
    emoji: "🦊",
    image: "/stories/raposa-porta-secreta.png",
    gradient: "from-orange-300 via-rose-300 to-fuchsia-400",
    minutes: 7,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Numa trilha escondida da floresta, uma pequena raposa encontrou uma porta azul encostada entre duas árvores, como se alguém a tivesse esquecido ali.",
      "Quando empurrou a maçaneta dourada, a porta se abriu para um campo secreto onde os animais podiam sussurrar seus maiores desejos ao vento.",
      "Uns pediam coragem, outros queriam amizade, e alguns desejavam apenas voltar a sorrir. A raposa observou tudo com olhos brilhando de curiosidade.",
      "Quando chegou sua vez, ela não pediu nada só para si. Desejou que todos ali encontrassem o que faltava em seus corações. E naquele instante, o campo inteiro se encheu de luz.",
    ],
  },
  {
    id: "menino-plantava-nuvens",
    title: "O Menino que Plantava Nuvens",
    author: "Ivo Horizonte",
    description:
      "Um menino descobre sementes mágicas capazes de fazer nascer nuvens e tenta salvar uma vila sem chuva.",
    categoryId: "natureza",
    emoji: "☁️",
    image: "/stories/menino-plantava-nuvens.png",
    gradient: "from-sky-200 via-cyan-300 to-blue-500",
    minutes: 7,
    isNew: true,
    isPublished: true,
    createdAt: null,
    updatedAt: null,
    pageCount: 4,
    pages: [
      "Téo morava numa vila onde a terra começava a rachar de sede, porque fazia muito tempo que nenhuma nuvem aparecia no céu.",
      "Um dia, encontrou um saquinho de sementes prateadas deixado pelo vento no quintal. Quando as plantou, pequenos tufos brancos começaram a crescer como algodão.",
      "Téo regou aquelas nuvens com esperança, canto e paciência. Logo elas subiram devagar para o céu, ficando maiores, mais macias e mais carregadas.",
      "Na primeira chuva, a vila inteira saiu para dançar. E Téo descobriu que até o céu floresce quando alguém acredita o suficiente para plantar o impossível.",
    ],
  },
];

export function getLegacyStory(id: string) {
  return legacyStories.find((story) => story.id === id);
}
