/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppConquistasRouteImport } from './routes/_app.conquistas'
import { Route as AppColecaoRouteImport } from './routes/_app.colecao'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppHistoriaIdRouteImport } from './routes/_app.historia.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppConquistasRoute = AppConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AppRoute,
} as any)
const AppColecaoRoute = AppColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoriaIdRoute = AppHistoriaIdRouteImport.update({
  id: '/historia/$id',
  path: '/historia/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/colecao': typeof AppColecaoRoute
  '/conquistas': typeof AppConquistasRoute
  '/perfil': typeof AppPerfilRoute
  '/historia/$id': typeof AppHistoriaIdRoute
}
export interface FileRoutesByTo {
  '/biblioteca': typeof AppBibliotecaRoute
  '/colecao': typeof AppColecaoRoute
  '/conquistas': typeof AppConquistasRoute
  '/perfil': typeof AppPerfilRoute
  '/': typeof AppIndexRoute
  '/historia/$id': typeof AppHistoriaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/colecao': typeof AppColecaoRoute
  '/_app/conquistas': typeof AppConquistasRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/': typeof AppIndexRoute
  '/_app/historia/$id': typeof AppHistoriaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/colecao'
    | '/conquistas'
    | '/perfil'
    | '/historia/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/biblioteca'
    | '/colecao'
    | '/conquistas'
    | '/perfil'
    | '/'
    | '/historia/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/biblioteca'
    | '/_app/colecao'
    | '/_app/conquistas'
    | '/_app/perfil'
    | '/_app/'
    | '/_app/historia/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conquistas': {
      id: '/_app/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AppConquistasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colecao': {
      id: '/_app/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof AppColecaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historia/$id': {
      id: '/_app/historia/$id'
      path: '/historia/$id'
      fullPath: '/historia/$id'
      preLoaderRoute: typeof AppHistoriaIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppColecaoRoute: typeof AppColecaoRoute
  AppConquistasRoute: typeof AppConquistasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHistoriaIdRoute: typeof AppHistoriaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppColecaoRoute: AppColecaoRoute,
  AppConquistasRoute: AppConquistasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppHistoriaIdRoute: AppHistoriaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
